title: Welcome at @friscolt # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
 Popurri of links about me:  <a href="https://twitter.com/Friscolt/status/1352856816246394885?s=20"> [EARTH team]</a> 

theme: jekyll-theme-minimal
