title: Welcome at @friscolt # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
 Abstract: First description <br>
 Mi nombre es Francisco. Actualmente vivo en <br>

 Keywords: 
 Medical imaging,
 Image processing and analysis,
 Machine learning,
 Computer vision,
 Digital signal precessing,
 Deep learning,
 Wavelet approach,
 Robotics,
 Biophotonics,
 Improve blood vessel visualization and localization,
 Matlab,
 Discrete wavelet transform


theme: jekyll-theme-minimal
