title: Francisco's Homepage # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
 Abstract: <br>
 Hello, my name is Francisco, and I'm from <a href= "https://www.instagram.com/p/CClVytAF1oy/">  Cholula 🇲🇽.  </a>  I process medical images at INAOE and Tec de Monterrey. <br> <br>
 
 Keywords: 
 
 Machine Learning, 
 Computer Vision 
 & Medical image processing
 

theme: jekyll-theme-minimal
