title: Welcome at @friscolt # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
 Popurri of links about me:  
 <a href= "https://twitter.com/Friscolt/status/1352856816246394885?s=20"> EARTH team </a> 
 <a href= "https://twitter.com/Friscolt/status/1120074887815520256?s=20"> friends and collaborators </a> 
 <a href= "https://twitter.com/Jose_Rangel_M/status/1164566151914876928?s=20"> DSG-INAOE </a> 
 <a href= "https://twitter.com/Friscolt/status/1131372838080794624?s=20"> Auckland, New Zealand </a> 

theme: jekyll-theme-minimal
