title: Gilberto's Homepage # your name (or website title) here
logo: "/logo.png?raw=true" # your photo (or logo) here
description: >
 About: <br>
 Dr. Gilberto Ochoa-Ruiz </a>  <br>
 Tecnologico de Monterrey </a>   <br>
 Guadalajara, Mexico <br> <br>

 

theme: jekyll-theme-minimal
