title: Gilberto's Homepage # your name (or website title) here
logo: "/files/logo.png?raw=true" # your photo (or logo) here
description: >
 About: <br>
 Dr. Gilberto Ochoa-Ruiz </a>  <br>
 Tecnologico de Monterrey, </a>  
 Guadalajara Mexico <br> <br>

 

theme: jekyll-theme-minimal
